### ISSUE TITLE
Allow multiple clients within a same context

### ISSUE THREAD

**Issue by pedroigor** [stianst/keycloak-tokens-cli#12]
The configuration seems to be based on clients so you can only operate using the client you have set for a context:

```
contexts:
    test-password:
        issuer: http://localhost:8080/realms/test
        client: test-password
        flow: password
        user: test-user
        user-password: test-user-password
```

As a user, I would like to be able to define a single context where all the clients associated with a given `issuer` are defined so that I don't have multiple `issuer` entries pointing to the same URL. The main motivation for this is:

* Make it easier to update a context so all users and clients associated with an issuer are grouped. For instance, if I want to change the URL for an issuer I don't need to go over multiple contexts.
* Make it easier to read the configuration file when you have multiple issuers and multiple users and clients for each one
* Setting context-level configuration settings that apply to all users and clients within a context easier

When executing commands within a context, I would also like to choose a client from the context rather than be forced to switch to a different context.

If the configuration is similar to this:

```
contexts:
    test:
        issuer: http://localhost:8080/realms/test        
        client: client-a
        user: user-a
        users:
            user-a:
                credentials:
                    password: mypassword
            user-b:
                credentials:
                    password: mypassword
        clients:
            flow: password
            client-a:
                 credentials:
                     secret: mysecret
            client-b:
                 credentials:
                     secret: mysecret
```

I can now run commands like(assuming `test` context is active):

```
# Use default client-a and user-a
kct token

# Use a different client
kct token --client client-b

# Use a different user
kct token --user user-b
```

For testing purposes, I'm also wondering if it makes sense to expose options to override/set the following options when using the `token` command:

* `flow` (perhaps it should be `grant-type` because `flow` in Keycloak is another thing and grant type is easy to map to the specs)
* `user`
* `user-password`

Otherwise, I'm forced to update the context configuration whenever I want to test a new one. Or perhaps #8 is enough to make it easier to set/update a context with additional configuration.

I hope it makes sense.

**Comment by stianst** [comment]
Ability to re-use issuer-url, client config, and user credentials makes sense, but don't think it'll work in the way you've proposed.

I don't really want to have a ton of config options to the commands, and would rather want just `--context`. In addition a context is used to associate stored tokens. If you try the latest release you can even do things like get the initial refresh token with a broad scope, then request tokens from that with a smaller scope. With that one thing I'd like to try to achieve is the ability to have a `SSO` scenario. Where you have one refresh token that is used for multiple purposes, but then each different purpose can get a subset of the scopes.

Need to think about this a little bit, but I could imagine something like:

```
issuers:
   local-test: http://localhost:8080/realms/test
   remote-test: http://remote/realms/test 
users:
  admin:
     user: admin
     password: admin
clients:
 myclient:
    id: myclient
   secret: mysecret
contexts:
  main:
     issuer-ref: local-test
     user-ref: admin
     client-ref: myclient
     scope: foo, bar
  sub:
    context-ref: main
    scope: foo
  custom:
     issuer: http://localhost:8080/realms/something
     client: anotherclient
     flow: device
```

That allows you to do the straightforward just configure a context, or use re-usable stuff. It does complicate the `CRUD` commands for config a bit, but may be worth it.

**Comment by stianst** [comment]
Take two:
```
issuers:
  local-test: 
    url: http://localhost:8080/realms/test
    clients:
      myclient:
        client-id: 
        flow: device
    users:
      pedro: 
        username: pedro
        password: test

contexts:
  main:
     issuer-ref: local-test
     user-ref: pedro
     client-ref: myclient
```
