### ISSUE TITLE
Add support for reusable users for a issuer

### ISSUE THREAD

**Issue by stianst** [stianst/keycloak-tokens-cli#16]
```
issuers:
  local-test: 
    ...
    users:
      admin: 
        username: admin
        password: admin

contexts:
  main:
     issuer-ref: local-test
     user-ref: admin
     ...
```
